version: '3.8'
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:6875
      - APP_KEY={APP_KEY}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=bookstackpass
      - DB_DATABASE=bookstackapp
    volumes:
      - bookstack_app:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=bookstackrootpass
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstackpass
    volumes:
      - bookstack_db:/config
    restart: unless-stopped
volumes:
  bookstack_app:
  bookstack_db:
